version: 2.1

executors:
  python:
    docker:
      - image: cimg/python:3.7
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
  ros:
    docker:
      - image: ros:noetic
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
      - image: eclipse-mosquitto
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD

jobs:
  test:
    executor:
      name: python
    steps:
      - checkout
      - run: make setup
      - run: make test
  rostest:
    executor:
      name: ros
    steps:
      - checkout
      - run:
          name: configure catkin workspace
          command: |
            mkdir -p ~/catkin_ws/src
            cd ~/catkin_ws
            ln -s /root/project src/mqtt_bridge
            source /opt/ros/noetic/setup.bash
            apt update
            rosdep update
            rosdep install --from-paths src --ignore-src -r -y
            catkin_make
            source devel/setup.bash
      - run:
          name: run rostest
          command: |
            cd ~/catkin_ws
            source /opt/ros/noetic/setup.bash
            source devel/setup.bash
            pip3 install mock
            rostest mqtt_bridge demo.test

workflows:
  version: 2
  build:
    jobs:
      - test
      - rostest
